dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_master:
    enabled: false
    scriptsDir: mosip_master      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_master          # customize e.g. mosip_master02
    dbUser: masteruser            # customize e.g. masteruser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/admin-services.git
    branch: develop

  mosip_audit:
    enabled: false
    scriptsDir: mosip_audit       # fixed - must match db_scripts/ folder in repo
    dbName: mosip_audit           # customize e.g. mosip_audit02
    dbUser: audituser             # customize e.g. audituser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/audit-manager.git
    branch: develop

  mosip_keymgr:
    enabled: false
    scriptsDir: mosip_keymgr      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_keymgr          # customize e.g. mosip_keymgr02
    dbUser: keymgruser            # customize e.g. keymgruser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/keymanager.git
    branch: develop

  mosip_kernel:
    enabled: false
    scriptsDir: mosip_kernel       # fixed - must match db_scripts/ folder in repo
    dbName: mosip_kernel           # customize e.g. mosip_kernel02
    dbUser: kerneluser             # customize e.g. kerneluser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/commons.git
    branch: develop

  mosip_idmap:
    enabled: false
    scriptsDir: mosip_idmap        # fixed - must match db_scripts/ folder in repo
    dbName: mosip_idmap            # customize e.g. mosip_idmap02
    dbUser: idmapuser              # customize e.g. idmapuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/id-repository.git
    branch: develop

  mosip_prereg:
    enabled: false
    scriptsDir: mosip_prereg       # fixed - must match db_scripts/ folder in repo
    dbName: mosip_prereg           # customize e.g. mosip_prereg02
    dbUser: prereguser             # customize e.g. prereguser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/pre-registration.git
    branch: develop

  mosip_idrepo:
    enabled: false
    scriptsDir: mosip_idrepo       # fixed - must match db_scripts/ folder in repo
    dbName: mosip_idrepo           # customize e.g. mosip_idrepo02
    dbUser: idrepouser             # customize e.g. idrepouser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/id-repository.git
    branch: develop

  mosip_ida:
    enabled: false
    scriptsDir: mosip_ida          # fixed - must match db_scripts/ folder in repo
    dbName: mosip_ida              # customize e.g. mosip_ida02
    dbUser: idauser                # customize e.g. idauser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/id-authentication.git
    branch: develop

  mosip_credential:
    enabled: false
    scriptsDir: mosip_credential   # fixed - must match db_scripts/ folder in repo
    dbName: mosip_credential       # customize e.g. mosip_credential02
    dbUser: credentialuser         # customize e.g. credentialuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/id-repository.git
    branch: develop

  mosip_regprc:
    enabled: false
    scriptsDir: mosip_regprc       # fixed - must match db_scripts/ folder in repo
    dbName: mosip_regprc           # customize e.g. mosip_regprc02
    dbUser: regprcuser             # customize e.g. regprcuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/registration.git
    branch: develop

  mosip_pms:
    enabled: false
    scriptsDir: mosip_pms          # fixed - must match db_scripts/ folder in repo
    dbName: mosip_pms              # customize e.g. mosip_pms02
    dbUser: pmsuser                # customize e.g. pmsuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    # Note: This flag is used to update datashare domain in partner policies according to deployment version (i.e v2/v3)
    # Set flag ENV_VERSION_FLAG to true for v2 envs and false for v3 envs.
    ENV_VERSION_FLAG: false
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/partner-management-services.git
    branch: develop

  mosip_hotlist:
    enabled: false
    scriptsDir: mosip_hotlist      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_hotlist          # customize e.g. mosip_hotlist02
    dbUser: hotlistuser            # customize e.g. hotlistuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/admin-services.git
    branch: develop

  mosip_resident:
    enabled: false
    scriptsDir: mosip_resident     # fixed - must match db_scripts/ folder in repo
    dbName: mosip_resident         # customize e.g. mosip_resident02
    dbUser: residentuser           # customize e.g. residentuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/resident-services.git
    branch: develop

  mosip_toolkit:
    enabled: false
    scriptsDir: mosip_toolkit      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_toolkit          # customize e.g. mosip_toolkit02
    dbUser: toolkituser            # customize e.g. toolkituser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/mosip-compliance-toolkit.git
    branch: develop

  mosip_digitalcard:
    enabled: false
    scriptsDir: mosip_digitalcard  # fixed - must match db_scripts/ folder in repo
    dbName: mosip_digitalcard      # customize e.g. mosip_digitalcard02
    dbUser: digitalcarduser        # customize e.g. digitalcarduser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/digital-card-service.git
    branch: develop

  mosip_esignet:
    enabled: false
    scriptsDir: mosip_esignet      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_esignet          # customize e.g. mosip_esignet02
    dbUser: esignetuser            # customize e.g. esignetuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet.git
    branch: develop

  mosip_mockidentitysystem:
    enabled: false
    scriptsDir: mosip_mockidentitysystem  # fixed - must match db_scripts/ folder in repo
    dbName: mosip_mockidentitysystem      # customize e.g. mosip_mockidentitysystem02
    dbUser: mockidentityuser              # customize e.g. mockidentityuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet-mock-services.git
    branch: develop

  mosip_otp:
    enabled: false
    scriptsDir: mosip_otp          # fixed - must match db_scripts/ folder in repo
    dbName: mosip_otp              # customize e.g. mosip_otp02
    dbUser: otpuser                # customize e.g. otpuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/otp-manager.git
    branch: develop

  inji_certify:
    enabled: false
    scriptsDir: inji_certify       # fixed - must match db_scripts/ folder in repo
    dbName: inji_certify           # customize e.g. inji_certify02
    dbUser: injicertifyuser        # customize e.g. injicertifyuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/inji-certify.git
    branch: develop

  inji_verify:
    enabled: false
    scriptsDir: inji_verify        # fixed - must match db_scripts/ folder in repo
    dbName: inji_verify            # customize e.g. inji_verify02
    dbUser: injiverifyuser         # customize e.g. injiverifyuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/inji-verify.git
    branch: develop

  inji_mimoto:
    enabled: false
    scriptsDir: inji_mimoto        # fixed - must match db_scripts/ folder in repo
    dbName: inji_mimoto            # customize e.g. inji_mimoto02
    dbUser: injimimotouser         # customize e.g. injimimotouser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/mimoto.git
    branch: develop
