{{- if .Values.databases.inji_verify.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-verify-init-env-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  MOSIP_DB_NAME: inji_verify
  DB_SERVERIP: {{ .Values.databases.inji_verify.host | quote }}
  DB_PORT: {{ .Values.databases.inji_verify.port | quote }}
  SU_USER: {{ .Values.databases.inji_verify.su.user | quote }}
  DML_FLAG: {{ .Values.databases.inji_verify.dml | quote }}
  GIT_REPO_URL: {{ .Values.databases.inji_verify.repoUrl | quote }}
  GIT_BRANCH: {{ .Values.databases.inji_verify.branch | quote }}
{{- end }}
